#!/bin/bash
echo "=== FRAME ALIGNMENT VERIFICATION ==="
echo ""
echo "Step 1: Check TF tree"
ros2 run tf2_tools view_frames
echo "  → Generated frames.pdf showing TF tree"
echo ""
echo "Step 2: Place obstacle DIRECTLY IN FRONT of robot"
echo "  Then check both maps in RViz:"
echo ""
echo "Step 3: Check /scan orientation"
echo "  ros2 topic echo /scan --once | grep -A 10 'ranges:'"
echo "  → Front rays (index ~180) should show obstacle distance"
echo ""
echo "Step 4: If obstacle appears BEHIND in both maps:"
echo "  → LIDAR physically backwards"
echo "  → Fix: Set lidar_angle_offset = π in both files"
echo ""
echo "Step 5: If obstacle appears different in /map vs /local_map:"
echo "  → Frame mismatch between Cartographer and our code"
echo "  → Check: Both use 'map' frame_id"
echo "  → Check: Robot pose source (both from /amcl_pose)"
